### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by samouri** [jzohdi/simple_graph#1]
Hi @jzohdi!

I want to start by saying this project is super cool! I had a lot of fun trying to use math to draw pretty pictures.  I had a couple of thoughts for things you could do to make this project more presentable and accessible:
1. Provide a [link to the hosted version](https://jzohdi.github.io/simple_graph/) in both the project description and in a README 
2. Create a README.md file providing some background to the project as well as suggested usage and also how to suggest/propose changes

Thank you again for all your work on this!

-Jake

PS. Here is the drawing I made 
![68747470733a2f2f73636f6e74656e742d6c6761332d312e78782e666263646e2e6e65742f762f74312e31353735322d392f34313235303532365f3234363638303636323730353636335f3137313636343232303730383932393533365f6e2e6a70673f5f6e635f6361743d30266f683d6431343037316](https://user-images.githubusercontent.com/4656974/45454565-603f5f80-b6b2-11e8-96bd-36856fd838c5.jpeg)

**Comment by jzohdi** [comment]
Hi @samouri, glad to see you're enjoying simple_graph! I have updated the READ.me 
as well as the hosted link on the github page. Also, you can now copy your URL and send it to a friend with the graph that you have created! 

Thanks again!
